# Generated by Django 4.0.4 on 2022-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type_of_customer',
            field=models.CharField(choices=[('Team', 'TEAM'), ('General', 'GENERAL'), ('Stilbaai', 'STILBAAI'), ('Accommodation', 'ACCOMMODATION')], default='GENERAL', max_length=200),
        ),
    ]
