# Generated by Django 4.0.3 on 2022-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_customer_type_of_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type_of_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='type_of_customer',
            field=models.ManyToManyField(to='mailer.typeofcustomer'),
        ),
    ]
