# Generated by Django 4.0.4 on 2022-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_typeofcustomer_remove_customer_type_of_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.CharField(max_length=200, null=True)),
                ('email_password', models.CharField(max_length=200, null=True)),
                ('email_host', models.CharField(max_length=200, null=True)),
                ('email_port', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
