# Generated by Django 4.0.4 on 2022-06-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_emailaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.EmailField(max_length=200, null=True)),
                ('email_password', models.CharField(max_length=200, null=True)),
                ('email_host', models.CharField(max_length=200, null=True)),
                ('email_port', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailAccounts',
        ),
    ]
